"use client";

import { useState } from "react";
import { useDashboardData } from "../../../lib/DashboardDataContext";
import { Card, CardContent, CardHeader, CardTitle } from "../../../components/ui/card";
import { Skeleton } from "../../../components/ui/skeleton";
import { Sparkles, FileText, ChevronDown, ChevronUp, Download } from "lucide-react";

const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";

type PolicyBrief = {
  executive_summary: string;
  key_findings: string[];
  recommended_actions: string[];
};

export default function InsightsPage() {
  const { insights, loading } = useDashboardData();
  const [briefLoading, setBriefLoading] = useState(false);
  const [brief, setBrief] = useState<PolicyBrief | null>(null);
  const [insightsExpanded, setInsightsExpanded] = useState(false);

  const handleGenerateBrief = async () => {
    setBriefLoading(true);
    setBrief(null);
    try {
      const res = await fetch(`${API_BASE}/api/policy-brief`);
      if (!res.ok) throw new Error("Failed to generate brief");
      const data = (await res.json()) as PolicyBrief;
      setBrief({
        executive_summary: data.executive_summary ?? "",
        key_findings: Array.isArray(data.key_findings) ? data.key_findings : [],
        recommended_actions: Array.isArray(data.recommended_actions) ? data.recommended_actions : [],
      });
    } catch {
      setBrief({
        executive_summary: "Unable to generate brief. Ensure the API is running.",
        key_findings: [],
        recommended_actions: [],
      });
    } finally {
      setBriefLoading(false);
    }
  };

  const handleExportPdf = async () => {
    if (!brief) return;
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF();
      let y = 20;
      doc.setFontSize(18);
      doc.text("Workforce Strategy Brief", 20, y);
      y += 8;
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text("Montgomery, Alabama — Workforce Pulse", 20, y);
      doc.text(new Date().toLocaleDateString(), 20, y + 6);
      y += 16;
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text("Executive Summary", 20, y);
      y += 6;
      doc.setFont("helvetica", "normal");
      doc.text(doc.splitTextToSize(brief.executive_summary, 170).join(" "), 20, y);
      y += doc.splitTextToSize(brief.executive_summary, 170).length * 5 + 10;
      if (brief.key_findings?.length) {
        doc.setFont("helvetica", "bold");
        doc.text("Key Findings", 20, y);
        y += 6;
        doc.setFont("helvetica", "normal");
        for (const f of brief.key_findings) {
          doc.text("• " + doc.splitTextToSize(f, 165).join(" "), 20, y);
          y += 6;
        }
        y += 4;
      }
      if (brief.recommended_actions?.length) {
        doc.setFont("helvetica", "bold");
        doc.text("Recommended Actions", 20, y);
        y += 6;
        doc.setFont("helvetica", "normal");
        for (const a of brief.recommended_actions) {
          doc.text("→ " + doc.splitTextToSize(a, 165).join(" "), 20, y);
          y += 6;
        }
      }
      y += 10;
      doc.setFontSize(8);
      doc.setTextColor(120, 120, 120);
      doc.text("Generated by Workforce Pulse — Bright Data + Azure AI", 20, y);
      doc.save("workforce-strategy-brief.pdf");
    } catch {
      if (typeof window !== "undefined") window.print();
    }
  };

  return (
    <div className="mx-auto w-full max-w-[1600px] gap-3 px-3 py-4 laptop:px-4 desktop:px-6">
      <div className="mb-6">
        <h1 className="text-xl font-semibold text-slate-100">AI Policy Insights</h1>
        <p className="text-sm text-slate-400">
          Generate an executive policy brief for city planners. Insights are synthesized into a structured report with recommendations.
        </p>
      </div>

      <div className="space-y-6">
        {/* Executive Policy Brief — main deliverable */}
        <Card className="border-sky-900/60 bg-slate-950/80 shadow-lg">
          <CardHeader className="flex flex-row items-center justify-between gap-4">
            <CardTitle className="flex items-center gap-2 text-sm font-semibold text-slate-200">
              <FileText className="h-4 w-4 text-sky-400" />
              Executive Policy Brief
            </CardTitle>
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={handleGenerateBrief}
                disabled={briefLoading}
                className="flex items-center gap-2 rounded-md bg-sky-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-sky-500 disabled:opacity-50"
              >
                <Sparkles className="h-3 w-3" />
                {briefLoading ? "Generating…" : "Generate Brief"}
              </button>
              {brief && (
                <button
                  type="button"
                  onClick={handleExportPdf}
                  className="flex items-center gap-2 rounded-md border border-slate-600 bg-slate-800/80 px-3 py-1.5 text-xs font-medium text-slate-200 hover:bg-slate-700"
                >
                  <Download className="h-3 w-3" />
                  Export PDF
                </button>
              )}
            </div>
          </CardHeader>
          <CardContent>
            {briefLoading ? (
              <div className="space-y-3">
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-5/6" />
                <Skeleton className="h-4 w-4/6" />
              </div>
            ) : brief ? (
              <div className="space-y-6 print:space-y-4">
                <div>
                  <h3 className="text-[10px] font-semibold uppercase tracking-wider text-sky-400/90">Executive Summary</h3>
                  <p className="mt-1.5 text-sm leading-relaxed text-slate-200">{brief.executive_summary}</p>
                </div>
                {brief.key_findings?.length > 0 && (
                  <div>
                    <h3 className="text-[10px] font-semibold uppercase tracking-wider text-sky-400/90">Key Findings</h3>
                    <ul className="mt-1.5 space-y-1.5">
                      {brief.key_findings.map((f, i) => (
                        <li key={i} className="flex gap-2 text-sm text-slate-200">
                          <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-sky-400" />
                          {f}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                {brief.recommended_actions?.length > 0 && (
                  <div>
                    <h3 className="text-[10px] font-semibold uppercase tracking-wider text-emerald-400/90">Recommended Actions</h3>
                    <ul className="mt-1.5 space-y-1.5">
                      {brief.recommended_actions.map((a, i) => (
                        <li key={i} className="flex gap-2 text-sm text-slate-200">
                          <span className="text-emerald-400">→</span>
                          {a}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                <p className="pt-2 text-[10px] text-slate-500">
                  Generated by Workforce Pulse — Bright Data + Azure AI
                </p>
              </div>
            ) : (
              <p className="text-sm text-slate-500">
                Click &quot;Generate Brief&quot; to create a structured policy brief with executive summary, key findings, and recommended actions for city planners.
              </p>
            )}
          </CardContent>
        </Card>

        {/* Live Insights — compact, collapsible source */}
        <Card className="border-slate-800/80 bg-slate-950/60">
          <button
            type="button"
            onClick={() => setInsightsExpanded(!insightsExpanded)}
            className="flex w-full items-center justify-between px-4 py-3 text-left"
          >
            <CardTitle className="flex items-center gap-2 text-sm font-medium text-slate-400">
              <Sparkles className="h-3.5 w-3.5 text-slate-500" />
              Source insights
            </CardTitle>
            {insightsExpanded ? (
              <ChevronUp className="h-4 w-4 text-slate-500" />
            ) : (
              <ChevronDown className="h-4 w-4 text-slate-500" />
            )}
          </button>
          {insightsExpanded && (
            <CardContent className="border-t border-slate-800/80 pt-3">
              {loading ? (
                <div className="space-y-2">
                  <Skeleton className="h-3 w-5/6" />
                  <Skeleton className="h-3 w-4/6" />
                  <Skeleton className="h-3 w-3/6" />
                </div>
              ) : insights && insights.length > 0 ? (
                <ul className="space-y-2">
                  {insights.map((item, idx) => (
                    <li key={idx} className="flex gap-2 text-xs text-slate-400">
                      <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-slate-500" />
                      {item}
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-xs text-slate-500">Run the pipeline to populate insights.</p>
              )}
            </CardContent>
          )}
        </Card>
      </div>
    </div>
  );
}
